// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC51iAVF2mOzeN7Ku2jnSQ0x8mI-LqYRlE',
    appId: '1:952464005112:web:43ae7705be526805ac680d',
    messagingSenderId: '952464005112',
    projectId: 'quotation-app-bc5b3',
    authDomain: 'quotation-app-bc5b3.firebaseapp.com',
    storageBucket: 'quotation-app-bc5b3.appspot.com',
    measurementId: 'G-WXK3FMBJR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQFAzqBGsPB5F7E0KDGuHI3X6OBWa7Wg',
    appId: '1:952464005112:android:2c70fc3aafe9e6ebac680d',
    messagingSenderId: '952464005112',
    projectId: 'quotation-app-bc5b3',
    storageBucket: 'quotation-app-bc5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB44T94PMuGHEhcdyz6YkEZ3x65DrIsGyE',
    appId: '1:952464005112:ios:e5bbb029d0ae18acac680d',
    messagingSenderId: '952464005112',
    projectId: 'quotation-app-bc5b3',
    storageBucket: 'quotation-app-bc5b3.appspot.com',
    iosBundleId: 'com.example.pract01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB44T94PMuGHEhcdyz6YkEZ3x65DrIsGyE',
    appId: '1:952464005112:ios:25169ced197ad35dac680d',
    messagingSenderId: '952464005112',
    projectId: 'quotation-app-bc5b3',
    storageBucket: 'quotation-app-bc5b3.appspot.com',
    iosBundleId: 'com.example.pract01.RunnerTests',
  );
}
